name: cmc-ccd-domain pipeline

trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
    
jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: |
      ls ./definition
      CCD_DEF_BASE_URL=http://localhost
      docker build -f definition/Dockerfile -t test-image definition/.
      docker run --rm test-image sh -c "cd /opt/ccd-definition-processor && yarn json2xlsx -D /data/sheets -o /cmc-ccd.xlsx"
    displayName: 'test'

#- job: Release
#  # Make sure we have a tag to run this job
#  condition: >
#    and(
#        succeeded(),
#        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
#      )
#  dependsOn: Validate
#  pool:
#    vmImage: 'Ubuntu 16.04'
#  steps:
#  - template: steps/charts/release.yaml@cnp-library
#    parameters:
#      chartName: ccd
#      chartReleaseName: chart-ccd
#      chartNamespace: chart-tests
