name: cmc-ccd-domain pipeline

trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
    
jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: |
      ls ./definition
      CCD_DEF_CLAIM_STORE_BASE_URL=http://localhost
      docker build -f definition/Dockerfile -t test-image .
      docker run --rm test-image sh -c "cd /opt/ccd-definition-processor && yarn json2xlsx -D /data/sheets -o /cmc-ccd.xlsx"
    displayName: 'test'

- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
  dependsOn: Test
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: ACR Build 
    displayName: 'ACR Build'
    enabled: true
    inputs:
      azureSubscription: azurerm-prod
      scriptLocation: 'inlineScript'
      inlineScript: az acr build -r $(acrName) -t $(Build.Repository.Name):$(imageTag) -g $(acrResourceGroup) -f definition/Dockerfile .
