name: cmc-ccd-domain pipeline

trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
    
jobs:
- job: Validate
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/validate.yaml@cnp-library
    parameters:
      chartName: ccd
      chartReleaseName: chart-ccd-ci-test
      chartNamespace: chart-tests
      helmInstallTimeout: "600"

- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
  dependsOn: Validate
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/release.yaml@cnp-library
    parameters:
      chartName: ccd
      chartReleaseName: chart-ccd
      chartNamespace: chart-tests