name: cmc-ccd-domain pipeline

variables:
  serviceConnection: 'azurerm-prod'
  repository: cmc/ccd-definition-importer
  acrName: hmctspublic
  acrResourceGroup: rpe-acr-prod-rg

trigger:
  branches:
    include:
    - refs/tags/*

pr:
  branches:
    include:
    - master

jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: |
      CCD_DEF_CLAIM_STORE_BASE_URL=http://localhost
      docker build -f definition/Dockerfile -t test-image .
      docker run --rm test-image sh -c "cd /opt/ccd-definition-processor && yarn json2xlsx -D /data/sheets -o /cmc-ccd.xlsx"
